services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: lemonlabs_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d lemonlabs_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  symptometer:
    build: .
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      POSTGRES_URL: "postgres://postgres:123@db:5432/lemonlabs_db"
      MEDGEMMA_API_URL: http://141.19.140.104:4000/v1/chat/completions
      MEDGEMMA_API_KEY: sk-s87RnNMaz4LhtjNMsl5HHg
      MEDGEMMA_API_MODEL: medgemma:27b
      FHIR_SERVER_URL: https://hapi.fhir.org/baseR4

volumes:
  postgres_data:
